prompts:
  chair:
    prompts:
      - chair
    is_instance: true
  desk:
    prompts:
      - desk
    is_instance: true
  monitor:
    prompts:
      - monitor
    is_instance: true
  unknown:
    prompts:
      - unknown
    is_instance: false
  garbage_bin:
    prompts:
      - trash can
    is_instance: true
  box:
    prompts:
      - box
    is_instance: true
  laptop:
    prompts:
      - laptop
    is_instance: true
  bag:
    prompts:
      - bag
    is_instance: true
  cardboard:
    prompts:
      - cardboard
    is_instance: true
